lib/api/ping.ex, lib/api/root.ex
will add `@GET /ping` which returns json response of `ping: pong`.
cc: @dblock
=> Adding ping endpoint

.travis.yml, config/config.exs, config/dev.exs, config/prod.exs, config/test.exs, lib/api/slack.ex, mix.exs, test/api/ping_test.exs, test/api/slack_test.exs, test/test_helper.exs
This mostly allows using Ecto in tests.
=> Added rudimentary tests for Slack slash command endpoint.

lib/event_receiver.ex
Currently we show `Firstname Lastname (email)` for subject, switch to only show first name.
```
Ashkan Nasseri (ashkan@gmail.com) Followed Abbas Kiarostami
``` 
will replace with
```
Ashkan Followed Abbas Kiarostami
```
=> Show only first name for event subject

lib/event_receiver.ex
=> Message look improvements

lib/api/slack.ex, lib/event_receiver.ex, lib/services/event_service.ex, lib/services/slack_command_service.ex
This should help us to proper unit test, will add those in separate PR.
=> Some refactoring and cleanup

lib/services/event_service.ex
=> Add as_user to options so messages are sent sa apr user

lib/services/slack_command_service.ex, test/services/slack_command_service_test.exs
change the format of summary response.
=> Better message format

.travis.yml, Dockerfile, circle.yml, deploy.sh, kubernetes.yml, scripts/ci_prepare.sh, scripts/ci_test.sh, scripts/deploy.sh
Following APR's deploy flow:
- Switch to CircleCi
- Add `deploy.sh` which uploads to ECR and then deploys to K8s
=> Switch to circleci

lib/services/event_service.ex
Follow up on https://github.com/artsy/gravity/pull/10653 and https://github.com/artsy/gravity/pull/10655.
=> Adding confirmed_buyer to inquiry slack message

lib/aprb.ex
Depends on:
https://github.com/artsy/gravity/pull/10721
=> Move subscriptions to listen on RabbitMQ

lib/aprb.ex
Follow up on https://github.com/artsy/gravity/pull/10757 and similar to #67
=> Listen for inquiries on RabbitMQ instead of Kafka

lib/aprb.ex
We have typo in setting up aprb gen servers and supervisors.
=> Fix wrong setup

config/dev.exs, config/prod.exs, lib/aprb.ex, lib/services/amq_event_service.ex, lib/services/slack_command_service.ex, lib/services/summary_service.ex, mix.exs, mix.lock
And remove Kafka connections...
=> Move purchases to rabbitmq

lib/services/summary_service.ex
We've been seeing lot of following errors:
```
* Changeset params
%{"summary_date" => ~D[2017-03-01], "topic_id" => 5, "total_count" => 0, "verb" => "purchased"}
* Changeset errors
[topic_verb_date: {"has already been taken", []}]
(ecto) lib/ecto/repo/schema.ex:127: Ecto.Repo.Schema.insert!/4
(aprb) lib/services/summary_service.ex:31: Aprb.Service.SummaryService.handle_summary/3
(elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
(elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
(stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.968788/0 in Aprb.Service.EventService.process_event/2>
```
This is happening because of the way we are trying to create event summary for the day for the first time.
Use cleaner version of `Repo.insert_or_update`
=> Fix issue in insert updating summary

lib/services/summary_service.ex
Added missing `invoices` in `SummaryService` this was causing issues in updating summary.
=> Add invoices to summary topics

lib/views/invoice_slack_view.ex
Had issue in calling `format_price`
=> Fix Format Price issue

config/dev.exs, config/prod.exs
It was running on localhost which caused issues with k8s.
=> Bind to 0.0.0.0 on prod and dev

lib/views/feedbacks_slack_view.ex, test/services/event_service_test.exs
- Fix name rendering
- Add emoji
=> Update format of the Slack view for feedback messages

lib/helpers/view_helper.ex, lib/views/invoice_slack_view.ex
We want to now listen on `invoicetransaction` events and when we get one we want to notify on slack about it.
=> Invoice transaction event

circle.yml, hokusai/config.yml
See https://github.com/artsy/hokusai/pull/40
=> update for Hokusai v0.4.0

lib/services/slack_command_service.ex
Include `routing_key` in `subscribe` and `subscriptions` response.
=> Properly show subscribed topic

lib/services/slack_command_service.ex
Not sure why original `|>` didn't work but this should be fine...
=> Fix weird preload issue

lib/services/slack_command_service.ex
=> Really fix subscription issue

config/dev.exs, config/test.exs
While getting this setup on my machine, @ashkan18 and I made this change. It seemed like maybe this change is worth a PR, so I'm opening this sucker, but if you don't want it, that's fine too.
=> Specify fewer things for dev setup

Dockerfile, hokusai/development.yml, hokusai/production.yml, hokusai/staging.yml, hokusai/test.yml
(Be sure to pull changes to local master first)
- `hokusai staging update`
- `hokusai production update`
=> #MIGRATION drop to deploy user and add node affinity

lib/helpers/view_helper.ex
=> Add missing space between artwork/artist

lib/helpers/view_helper.ex, lib/services/event_service.ex, lib/views/sales_slack_view.ex, test/services/event_service_test.exs
And also better slack message formatting.
=> Fix Routing key issue

lib/views/commerce_slack_view.ex
=> Fix not matching for states we don't care about in commerce slack

lib/views/sales_slack_view.ex
=> Fixed hardcoded test id 😐

lib/views/consignments_slack_view.ex
Follow up on: https://github.com/artsy/convection/pull/214
=> Add images to consignment messages

lib/helpers/view_helper.ex, lib/views/commerce_slack_view.ex
Adds admin link to orders messages
=> Update commerce slack messages to include admin link

hokusai/production.yml
We are currently running with two pods, but since this is relatively small app and not many calls into it, going to scale it down to 1 pod. 
People say Elixir is really efficient when it comes to using resources, I believe that and going to trust it :)
```
hokusai production update
```
=> Downscale APRB

lib/views/commerce_slack_view.ex
Replace buyer's full name with their first name and add partner admin to the message+ some cleanup
=> Remove buyer's full name and add admins

lib/views/commerce_slack_view.ex, lib/views/feedbacks_slack_view.ex
And also cleanup user name in feedback messages
=> Switch to v1 for partner

lib/views/commerce_slack_view.ex
Currently we use `state` to detect what message we should show in slack. That doesn't work since some events end up having the same state. 
When we want to send reminders for pending fulfillment orders, the state for all of them is `approved`.
Switch to `verb` for setting message, remove old unused ones and add new ones.
=> Switch to use verb instead of state for slack messages

lib/views/consignments_slack_view.ex
=> Update consignment events

lib/views/consignments_slack_view.ex
Fixed image urls issue and offer link for consignments
=> Fix images and make offer link

lib/services/slack_command_service.ex
Format help command and describe `topic:routing_key` option.
=> Format help command

lib/views/commerce_slack_view.ex
=> Properties, not proplists

lib/views/commerce_slack_view.ex
Show message when we receive a counteroffer
=> Add offer.submitted events

lib/views/commerce_slack_view.ex
small change, so mall thats not even a change...
=> Move things for more readable messages

config/dev.exs, config/prod.exs
Currently APRB API is not exposed
=> Followup to fix port listening and etc

config/prod.exs
=> another try

config/prod.exs
this is another follow up on update to Elixir 1.7 and new maru
=> Update port and `bind_addr` to correct value

lib/views/commerce_slack_view.ex
=> Update message format

lib/views/commerce_slack_view.ex
added missing rejection reasons
=> Add new rejection reasons + offer waiting response

lib/views/bidding_slack_view.ex
=> Update bidding messages to include currency and estimate

.gitignore, lib/views/bidding_slack_view.ex
=> Add high and low estimates

lib/helpers/view_helper.ex, lib/views/commerce/commerce_order_slack_view.ex
https://artsyproduct.atlassian.net/browse/PURCHASE-1214
make partner name and user name links to their exchange orders page.
=> Better links for partner and user name

lib/helpers/view_helper.ex, lib/views/commerce/commerce_helper.ex, lib/views/commerce/commerce_offer_slack_view.ex, lib/views/commerce/commerce_order_slack_view.ex, lib/views/commerce/commerce_transaction_view.ex, test/views/commerce_slack_view_test.exs
Added few more details to Failed transaction events
Co-authored-by: Joey Aghion <joey@aghion.com>
=> Updated failed transaction to add more details

lib/views/commerce/commerce_transaction_view.ex
More changes to include total amount, admin, fix partner name and etc.
=> More updates to transaction message

lib/views/purchase_slack_view.ex
=> [Deploy] Fix purchase slack amount issue

hokusai/production.yml
This should fix the bug in config from this build: 
https://circleci.com/gh/artsy/aprb/364
=> Fix duplicate http issue

config/prod.exs
Now that port issues are resolved and nginx is configured, I'd like to try adding this again...
Related conversation: https://artsy.slack.com/archives/CA8SANW3W/p1569506397001000
Related ticket: https://artsyproduct.atlassian.net/browse/PLATFORM-1782
=> Put back https scheme
