artsy/aprb

- lib/api/slack.ex
- lib/event_receiver.ex
- lib/models/subscriber.ex
- lib/models/subscription.ex
- lib/models/topic.ex
- test/api/slack_test.exs
- Add logic to subscribe/unsubscribe. 
- Added test for subscribe. 
- Add logic for sending events to slack based on channel subscriptions.
- Switched to check subscriptions based on channel and not user
- Add more test (unsubscribe, list, etc)
- Fix issue with test DB, test db doesn't cleanup after each test, so we end up with many topics.
- Add unique constraint on `name` to `Topics`
> Subscription logic

- lib/aprb.ex
- lib/services/event_service.ex
- lib/services/slack_command_service.ex
- priv/repo/migrations/20160818190952_add_purchases_topic.exs
- Added Kafka Event receiver for `purchases` topic
- Modified `EventService` to process `purchases` events.
> Adding purchase events

- lib/services/slack_command_service.ex
- test/api/slack_test.exs
When user tries to unsubscribe from topics that they haven't subscribed to or don't exist, we were still showing successful unsubscribe message but the list of unsubscribed topics were empty.
Fixes #32
Now if unsubscribe logic didn't unsubscribe from any topic, we will show a message saying:
> Can't unsubscribe! You were not subscribed to _name of topic_ or topic doesn't exist.
> Show proper message for unsubscribe

- config/config.exs
- lib/clients/gravity.ex
- lib/services/event_service.ex
Current bidding slack notifications include `lotId` which is not useful, we want to switch to artsy's sale artwork link which will be unfuled and has artwork/artist data.
Add a Gravity client which is basically a HTTPPoison wrapper, we use this to call sale artwork endpoint in gravity using event's `lotId` and get sale artworks `permalink`. With that we add permalink to slack message.
We need to add two new env variables to APRb stack setting:
`GRAVITY_API_URL` and `GRAVITY_API_TOKEN`.
We need to add tests for this and also switch to a proper HAL based Gravity Client.
> Add sale artwork link to slack message

- config/dev.exs
- lib/models/summary.ex
- lib/services/event_service.ex
- lib/services/slack_command_service.ex
- lib/services/summary_service.ex
- mix.exs
- mix.lock
- priv/repo/migrations/20160919005829_add_summaries_table.exs
- test/api/slack_test.exs
- test/services/event_service_test.exs
- test/services/slack_command_service_test.exs
- test/services/summary_service_test.exs
- test/support/factory.ex
- test/test_helper.exs
We want to be able to store count of (topic, verbs) for each day. So instead of showing all artist follows we could ask for total number of follows for specific day.
Fixes #30 
Added new `Summary` model which holds `topic_id`, `verb`, `total_count` and `summary_date`. Basically every time we get a new event we call new `SummaryService.update_summary` which basically parses the event and creates/updates a row in `summaries` table.
Also added a new slack command:
```
/aprb summary <topic> <optional date in YYYY-MM-DD format>
```
which will return total counts for each `verb` in that topic.
- Added new test files for `SlackService`, `EventService` and newly added `SummaryService`. We still need to add more test cases but this should be a good start.
- Switched to staging Kafka for dev.
> Support event rollup

- lib/aprb.ex
- lib/services/event_service.ex
- lib/services/summary_service.ex
- priv/repo/migrations/20160928174439_add_conversations_topic.exs
- test/services/event_service_test.exs
Get slack notifications everytime a collector responded `other` with a comment to our Quick Follow up emails.
https://github.com/artsy/impulse/pull/120 adds new `conversations` topic and will post events to this topic everytime we get a new buyer outcome. Here we are listening on new `conversations` topic and send proper message to slack about it.
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
> Buyer outcome events

- circle.yml
We need to upgrade to docker 1.10 to be able to generate multiple tags for same image. Following https://discuss.circleci.com/t/docker-1-10-0-is-available-beta/2100
> Update circleci docker

- circle.yml
Circleci builds are [failing](https://circleci.com/gh/artsy/aprb/13) on PRs (#49) because environment variables are [not available](https://circleci.com/docs/fork-pr-builds/) in PR fork builds and missing `AWS_ACCOUNT_ID` is causing build command to fail.
Move building docker image to deploy process which will only happen for master branch builds.
> Move builindg docker images to deploy process

- lib/aprb.ex
- lib/services/event_service.ex
- test/services/event_service_test.exs
Follow up on https://github.com/artsy/aprb/pull/41, we are now posting `conversations` event from Gravity and we are ready to enable this feature again.
> Conversations events

- lib/services/event_service.ex
With current logic for `subscriptions` events, it's possible to return`nil` for `processed_message` here https://github.com/artsy/aprb/blob/master/lib/services/event_service.ex#L5 when `verb` is not `buyer_outcome_set` or outcome wasn't `other`.
Check for nil `processed_message` and only call slack if it was not nil!
Add test to make sure slack is not called for empty processed message.
> Fix nil messages to slack

- Dockerfile
In new k8s approach for deploying APRB we are missing db migration step.
Run `mix ecto.migrate` before starting app in container in Dockerfile
> Migrate db in deploy process

- terraform/.terragrunt
- terraform/00-main.tf
- terraform/01-production.tf
- terraform/README.md
- Adds terragrunt config
- Adds aprb-production via terraform
Achtung!
The existing RDS db is already imported into terraform state so `terragrunt plan` should show no changes.
Do *not* run `terraform apply` before merging this PR, or else it will delete the aprb-production database already created!
> Add terraform and RDS instance

- lib/services/event_service.ex
Add more details to inquiry request slack messages to include Professional Buyer flag and also initial message snippet.
Follow changes from https://github.com/artsy/gravity/pull/10653/
> Update inquiry request slack message with details

- lib/aprb.ex
We started getting these errors after prev deploy:
```
Jan 09 12:14:59 k8s-worker-0.prd.artsy.systems docker/k8s_aprb.8e3e6832_aprb-492304161-l46cb_default_9ba25de3-d:      ** (EXIT) an exception was raised:
Jan 09 12:14:59 k8s-worker-0.prd.artsy.systems docker/k8s_aprb.8e3e6832_aprb-492304161-l46cb_default_9ba25de3-d:          ** (ArgumentError) duplicated id :conversations found in the supervisor specification, please explicitly pass the :id option when defining this worker/supervisor
```
Could not use same id for workers even if they are for different GenServer modules. Changing new conversation amq based GenServer id.
>  Fix duplicate id for GenServer issue

- Dockerfile
Elixir image in Dockerhub has been updated recently which has caused few issues for us. Some weird errors with `merge` and keyword arguments. Switching to `1.3.0` instead of latest.
> Use elixir:1.3.0 image instead of the latest

- lib/services/event_service.ex
- lib/views/radiation_message_slack_view.ex
use `to_email_address` instead of `to_email` when getting it from `event`.
> Fix issue with not showing email in spam/bounce events

- lib/views/bidding_slack_view.ex
The `amountCents` we receive from Causality is in cents 😄 so we have to divide by 100. (Note that this is another thing that will break when we decide we want to support Yen).
> @ashkan18 => divide bidding amounts by 100

- lib/aprb.ex
- lib/services/event_service.ex
- priv/repo/migrations/20170214204816_rename-bidding-to-auctions.exs
We are moving form Kafka to RabbitMQ for `bidding` events. Also in https://github.com/artsy/causality/pull/348, bidding topic has been renamed to `auctions`, in this PR we stop listening on `bidding` on Kafka and start listening on `auctions` on rabbitmq, currently we don't do anything with routing key since there is only one event (second bidder) is produces but later on we may want to revisit this if we started getting more events.
related to: https://github.com/artsy/causality/pull/348
> Support rabbitmq bidding events

- lib/services/summary_service.ex
Make sure Summary logic handles new `auctions` topic properly.
> Fix storing Summary for new auctions topic

- lib/aprb.ex
- lib/services/amq_event_service.ex
Currently we only listen on `"*"` as RabbitMQ `routing_key`. We want to be able to listen to a topic and specific `routing_key`.
Instead of only passing `topic` when starting a new `AmqEventService`  pass Map of `topic` and optional `routing_key` then when creating connection, use default `*` for routing key and update it with passed in param.
> Add optional routing_key to start_link opts

- lib/services/amq_event_service.ex
We were passing `opts` instead of `topic` to consume method which would cause 
```
where: t.name == ^%{routing_key: "SecondPriceBidPlaced", topic: "auctions"},
```
cc: @bhoggard
> Fix passing opts instead of topic to consume event

- lib/services/summary_service.ex
- test/services/event_service_test.exs
We added logic to process summary for `subscriptions` differently in https://github.com/artsy/aprb/pull/79, but we still had it in the check for normal summary calculation.
Removed it from there.
> Remove Subscription from normal handling for summary

- lib/views/purchase_slack_view.ex
Depends on https://github.com/artsy/gravity/pull/11054
Adding:
- Partner Name
- Contract type
- Outreach admin
to slack message for purchase events.
> Add partner/admin detail to Purchase slack view

- lib/aprb.ex
- lib/services/event_service.ex
- lib/services/summary_service.ex
- lib/views/invoice_slack_view.ex
- priv/repo/migrations/20170523182402_add-invoices-topic.exs
Start listening on new `invoices` topic and post to slack when getting new event.
Add new `invoices` to `topics`
Remove `bidding` now that we've moved to `auctions`
> Add listening on invoices topic and post messages

- lib/helpers/view_helper.ex
- lib/views/invoice_slack_view.ex
Added Artwork title and artists for artwork groups.
> Add artworks titles to slack message

- lib/helpers/view_helper.ex
We used `'` for string after switching gear from Ruby to Elixir, In Elixir `'` is a Character list and is not binary while `"` is binary and String.
http://culttt.com/2016/03/21/working-strings-elixir/
This fixes that
> Switch to string from character list

- hokusai/production.yml
- hokusai/staging.yml
This will ensure new contains come up before the old ones are terminated, when doing a `hokusai deploy` `hokusai refresh` etc
cc @joeyAghion you will want to add this to Diffusion as well
> ensure zero-downtime rollingupdate

- lib/api/root.ex
DNS stopped serving APRb since there is no @GET on root. This most likely happened after few dependencies updates recently.
Add a simple root endpoint so DNS keeps finding APRb 👀
> Add root endpoint to make DNS happy

- lib/aprb.ex
- lib/services/amq_event_service.ex
- lib/services/event_service.ex
- lib/views/invoice_slack_view.ex
- test/services/event_service_test.exs
Following up with changes in how we are setting event's `routing_key` in [this impulse PR](https://github.com/artsy/impulse/pull/307) and [changes in lewitt-api](https://github.com/artsy/lewitt-api/pull/254), this PR now:
- listens on proper `routing_key` for `conversations` topic
- now we pass `routing_key` of current event to `EventService.receive_event` so we can render proper message based on routing key
- Added new `merchant_account_message` to `InvoiceSlackView` which we decide if we should use it or not based on new shiny `routing_key`
This change has to be deployed AFTER two PRs mentioned above are deployed.
> Switch to use routing keys

- lib/services/amq_event_service.ex
This took me forever to figure out but listening on `*` means listening on one word routing key, while listening on `#` means listening on everything.
> * (star) can substitute for exactly one word. # (hash) can substitute for zero or more words.
from https://www.rabbitmq.com/tutorials/tutorial-five-python.html
> Switch to '#' for default routing key

- lib/views/invoice_slack_view.ex
The key coming in is `merchantaccount` and not `merchant_account`.
> proper routing key matching for merchant account events

- lib/services/sentiment_analysis_service.ex
- lib/views/feedbacks_slack_view.ex
- mix.exs
- mix.lock
- test/services/event_service_test.exs
- test/services/sentiment_analysis_service_test.exs
This imports the [Sentient](https://github.com/dantame/sentient) library into APRb in order to do some rudimentary sentiment analysis on incoming feedback messages.
This performs the analysis inline, based on some simple static text analysis and might be improved by calling out to a sentiment analysis API.
> Add some lightweight sentiment analysis to incoming feedback messages

- lib/views/feedbacks_slack_view.ex
- test/services/event_service_test.exs
Closes #108 
In order to address concerns about email addresses being exposed / responded to, we now:
- no longer show the sender's email address (which also takes care of the annoying empty `<>` in the case of user deletion messages).
- obfuscate any other email addresses that appear in the message body
> Filter out email addresses from the Slack view

- lib/views/purchase_slack_view.ex
Following request for adding admins to purchase slack messages and https://github.com/artsy/gravity/pull/11544
> Add Admin to purchase events

- lib/aprb.ex
- lib/services/amq_event_service.ex
We've added new events to our messages topic which we don't want to listen on and post slack notification for them but since we are listening on all routing keys at this point we end up posting all of them to the channel.
Allow binding to multiple routing keys instead of just one and use it to limit messages topic binding.
Delete current binding first.
> Support multiple routing keys when binding to queue

- lib/aprb.ex
correct routing key is `delivery.spamreport`
> Fix wrong routing key for radiation.messages

- .gitignore
- Dockerfile
- config/config.exs
- lib/aprb.ex
- lib/helpers/view_helper.ex
- lib/services/event_service.ex
- lib/services/summary_service.ex
- lib/views/sales_slack_view.ex
- priv/repo/migrations/20180713162611_add_sales_topic.exs
- test/services/event_service_test.exs
- test/support/service_case.ex
- test/test_helper.exs
- Adds listening on new `sales` topic
- Post slack messages for `sale.ended` and `sale.started` events.
Used Slack's `<url|title>` approach to remove some long ur's and make them actual links.
> Add listening on sales events

- lib/views/sales_slack_view.ex
Fetch `sale` endpoint and get number of lots and sale type to show in the notification
> Add sale type and number of lots

- lib/views/commerce_slack_view.ex
We started posting events on failed transaction https://github.com/artsy/exchange/pull/233, we need to post slack messages for these events.
Update existing commerce slack view to also handle `transaction.failed` routing keys.
> Failed transactions messages

- lib/views/commerce_slack_view.ex
The routing key for failed transaction is `transaction.created`, switch to correct one.
Followup on #143
> Update routing key

- lib/views/commerce_slack_view.ex
- lib/views/invoice_slack_view.ex
Followup on #145 , artworks links are not unfurled in commerce messages.
also fixes https://github.com/artsy/aprb/issues/129
Artwork links have extra space in them causing unfurl not to work.
Invoice message issue's cause is we where getting `id` from `artwork_group` but had to get `artwork_id`
> Fix invoice message issue and missing artwork links

- lib/views/commerce_slack_view.ex
- lib/views/consignments_slack_view.ex
Most updates mentioned https://artsyproduct.atlassian.net/browse/PURCHASE-750 except showing messages on counter offer, right now we use `order.submitted` for them.
> Order and consignment message updates

- lib/views/consignments_slack_view.ex
After changes in #150 , we switched to send `sign` and `coa` flags directly in the hash instead of their string representations. Slack seems to change booleans to 0/1 in their message attachments.
Switch back to string for those 2 fields.
> Fix CAO and sign showing as 1 in the messages

- lib/api/root.ex
- lib/views/commerce_slack_view.ex
We want to show available purchase options for each artwork in the order and also show what type or purchase option we got.
Do it!
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
> Add available purchase types per line item

- lib/views/commerce_slack_view.ex
When showing available purchase options if artwork is not available for sale anymore we don't show purchase options available at the time of purchase.
Instead of using `offerable` and `aqucialitelkwjklaable` (i can't spell this one), use `offer` and `ecommerce` flag of the artwork
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
> Use ecommerce and offer flag instead of offerable

- lib/views/commerce/commerce_transaction_view.ex
Per CRT's request, they want to know when a failed transaction happens was it BN or MO
> Add mode to transaction events

- lib/helpers/view_helper.ex
- lib/views/bidding_slack_view.ex
- lib/views/commerce/commerce_offer_slack_view.ex
- lib/views/commerce/commerce_order_slack_view.ex
- lib/views/commerce/commerce_transaction_slack_view.ex
- lib/views/inquiry_slack_view.ex
- lib/views/invoice_slack_view.ex
- lib/views/purchase_slack_view.ex
- test/support/fixtures.ex
- test/views/commerce/commerce_transaction_slack_view_test.exs
- test/views/commerce_slack_view_test.exs
Current commerce messages show amounts in $ even if it was in GBP.
Remove weirdness around `format_price` and how needs things in dollar but then multiplies by 100 and pass `currency_code` to all `format_price` calls.
> Support other currencies and fix weird divide by 100

- .circleci/config.yml
- README.md
Updates `push` and `deploy` steps to use orbs, and implement PR-based release process.
Circle config has been updated to use 2.1 features.
> Use Circle orbs
